# The URL the site will be built for
base_url = "https://proycon.anaproy.nl"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true
feed_filename = "rss.xml" #old one was index.xml, ensure redirect is present!

title = "Proycon's website"
description = "Language enthusiast, polyglot, linux user, open-source advocate, programmer, computational linguist, amateur pianist, gay"

[extra]
# Put all your custom variables here
author = "Maarten van Gompel (proycon)"
email = "proycon@anaproy.nl"
year = 2020
menu = [
   {url = "/", name = "Home"},
   {url = "/about", name = "About"},
   {url = "/photos", name = "Photos"},
   {url = "/posts", name = "Posts"},
   {url = "/software", name = "Software"},
   {url = "/publications", name = "Publications"},
   {url = "/work", name = "Work"},
   {url = "/languages", name = "Languages"},
   {url = "/links", name = "Links"},
]

networks = [
    {name = "E-Mail", url = "mailto:proycon@anaproy.nl", value = "proycon@anaproy.nl", icon_pack="fas", icon="fa-envelope", profile=true},
    {name = "GnuPG Key", url = "/key.asc", value="39FE11201A31555C", icon_pack="fas", icon="fa-key", profile=false},
    {name = "XMPP", url = "xmpp:proycon@anaproy.nl", value="proycon@anaproy.nl", icon_pack="fas", icon="fa-comments", profile=false},
    {name = "Matrix", url = "matrix:user/proycon:matrix.anaproy.nl", value="@proycon:matrix.anaproy.nl", icon_pack="fas", icon="fa-comments", profile=false},
    {name = "IRC", url = "irc://irc.freenode.org/proycon", value="proycon on FreeNode", icon_pack="fas", icon="fa-comments", profile=false},
    {name = "Telegram", url = "https://telegram.me/proycon", value = "@proycon", icon_pack="fab", icon="fa-telegram", profile=true },
    {name = "Fediverse (Mastodon)", url = "https://social.anaproy.nl/@proycon", value = "@proycon@social.anaproy.nl", icon_pack="fab", icon="fa-mastodon", profile=true},
    {name = "Twitter", url = "https://twitter.com/proycon", value = "@proycon", icon_pack="fab", icon="fa-twitter", profile=true},
    {name = "GitHub", url = "https://github.com/proycon", value = "proycon", icon_pack="fab", icon="fa-github", profile=true},
    {name = "ORCID", url = "https://orcid.org/0000-0002-1046-0006", value = "0000-0002-1046-0006", icon_pack="fab", icon="fa-orcid", profile=true},
    {name = "Bitcoin", url = "bitcoin:1BRptZsKQtqRGSZ5qKbX2azbfiygHxJPsd", value="1BRptZsKQtqRGSZ5qKbX2azbfiygHxJPsd", icon_pack="fab", icon="fa-btc", profile=false},
]

